### ISSUE TITLE
code using global standards

### ISSUE THREAD

**Issue by cervidae** [jonnboy612/studio_ghibli#1]
Your syntax is a mess. Don't mix multiple styles together

HTML
* ids are primarily used by JS and should therefore use camel casing like J's
* Css uses kebab case

CSS
* Consider learning css shorthand 

JS
* Single quotation vs double quotations. Choose 1. Single quotation is more common.
* don't use var anymore. Use let for things that get reassigned and const for things that don't. 
* Either use semi colons or don't. Choose one and stick with it. 
* Your tabs don't line up

**Comment by jonnboy612** [comment]
fixed syntax issues
